### ISSUE TITLE
`MESSAGEQUEUE_HOST: edgex-redis` is missing in docker-compose

### ISSUE THREAD

**Issue by MonicaisHer** [edgexfoundry-holding/device-usb-camera#21]
I added device-camera-usb into docker-compose following the [guide](https://github.com/edgexfoundry/device-usb-camera/blob/main/docker-compose/README.md).There is a message bus related issue when I running docker:
```
level=INFO  app=device-usb-camera source=driver.go:533 msg="start video streaming for device MyTestCamera"
level=ERROR  app=device-usb-camera source=utils.go:71 msg="Failed to publish event to MessageBus: dial tcp 127.0.0.1:6379: connect: connection refused"
```
There is a manual solution: adding the following environment variable into docker-compose.yaml:
```
  device-usb-camera:
    environment:
      MESSAGEQUEUE_HOST: edgex-redis
```
I notice that in other [device docker files](https://github.com/edgexfoundry/edgex-compose/blob/main/compose-builder/add-device-mqtt.yml), `MESSAGEQUEUE_HOST` is contained neither and devices run without error, so I am not sure where to add the `MESSAGEQUEUE_HOST`.

**Comment by lenny-goodell** [comment]
Note that this [Compose Builder PR](https://github.com/edgexfoundry/edgex-compose/pull/243) resolves this issue. Just waiting on LF ticket that is blocking the CI building the docker images.

**Comment by lenny-goodell** [comment]
@MonicaisHer , I think this issue can now be closed per this PR:
https://github.com/edgexfoundry/edgex-compose/pull/243

**Comment by MonicaisHer** [comment]
@lenny-intel Thank you for the changes. It is working great with [ONVIF camera](https://github.com/lenny-intel/edgex-compose/blob/main/compose-builder/add-device-onvif-camera.yml#L35). However, the issue still persists with [USB camera](https://github.com/lenny-intel/edgex-compose/blob/main/compose-builder/add-device-usb-camera.yml#L34-L35). Would that make sense also add `MESSAGEQUEUE_HOST` for USB camera?

**Comment by lenny-goodell** [comment]
@MonicaisHer , `MESSAGEQUEUE_HOST` is being set correctly when I run ` make gen no-secty ds-usb-camera` from latest Compose Builder. Please verify you have latest edgex-compose and still have issue when your run `make gen no-secty ds-usb-camera`

```
  device-usb-camera:
    container_name: edgex-device-usb-camera
    depends_on:
    - consul
    - data
    - metadata
    device_cgroup_rules:
    - c 81:* rw
    environment:
      CLIENTS_CORE_COMMAND_HOST: edgex-core-command
      CLIENTS_CORE_DATA_HOST: edgex-core-data
      CLIENTS_CORE_METADATA_HOST: edgex-core-metadata
      CLIENTS_SUPPORT_NOTIFICATIONS_HOST: edgex-support-notifications
      CLIENTS_SUPPORT_SCHEDULER_HOST: edgex-support-scheduler
      DATABASES_PRIMARY_HOST: edgex-redis
      EDGEX_SECURITY_SECRET_STORE: "false"
      MESSAGEQUEUE_HOST: edgex-redis
      REGISTRY_HOST: edgex-core-consul
      SERVICE_HOST: edgex-device-usb-camera
    hostname: edgex-device-usb-camera
    image: nexus3.edgexfoundry.org:10004/device-usb-camera:latest
    networks:
      edgex-network: {}
    ports:
    - 127.0.0.1:8554:8554/tcp
    - 127.0.0.1:59983:59983/tcp
    read_only: true
    restart: always
    security_opt:
    - no-new-privileges:true
    user: root:root
    volumes:
    - /dev:/dev:rw
    - /run/udev:/run/udev:ro
```
